import { CustomerItem, PropertyItem } from './types';

export const INITIAL_CUSTOMERS: CustomerItem[] = [
  {
    id: 'cust-1',
    name: '김태호',
    carrier: 'SK',
    phone: '010-8921-3450',
    type: 'SELLER',
    group: 'RECEIVED',
    memo: '자금 사정으로 아파트 빠른 매매 원함. 주말 방문 시 사전 연락 요망.',
    createdAt: '2026-09-28T09:30:00Z',
    updatedAt: '2026-09-28T09:30:00Z',
  },
  {
    id: 'cust-2',
    name: '박서연',
    carrier: 'KT',
    phone: '010-3456-7890',
    type: 'LESSOR',
    group: 'RECEIVED',
    memo: '상가 1층 디저트 카페 임차 만기 임박. 프랜차이즈나 베이커리 선호.',
    createdAt: '2026-09-29T14:15:00Z',
    updatedAt: '2026-09-29T14:15:00Z',
  },
  {
    id: 'cust-3',
    name: '이진우 대표',
    carrier: 'LG',
    phone: '010-5678-1234',
    type: 'LESSOR',
    group: 'RECEIVED',
    memo: '테헤란로 인근 중소 IT 스타트업 사무실 임대. 룸 3개 인테리어 완비됨.',
    createdAt: '2026-09-30T11:00:00Z',
    updatedAt: '2026-09-30T11:00:00Z',
  },
  {
    id: 'cust-4',
    name: '정민수',
    carrier: 'SK알뜰폰',
    phone: '010-9012-4567',
    type: 'BUYER',
    group: 'SEARCHING',
    memo: '신혼부부. 30평대 아파트 매매 희망. 초등학교 도보 5분 이내 단지 필수.',
    createdAt: '2026-10-01T10:00:00Z',
    updatedAt: '2026-10-01T10:00:00Z',
    demands: [
      {
        id: 'dem-1',
        customerId: 'cust-4',
        targetPropertyType: 'APARTMENT',
        targetTransactionType: '매매',
        targetRegion: '송파구 잠실/가락동',
        minBudget: 130000,
        maxBudget: 160000,
        preferredArea: 84.9,
        requirements: '역세권, 판상형 4베이 구조 선호',
        status: 'ACTIVE',
        createdAt: '2026-10-01T10:00:00Z',
        updatedAt: '2026-10-01T10:00:00Z',
      },
    ],
  },
  {
    id: 'cust-5',
    name: '최은경',
    carrier: 'LG알뜰폰',
    phone: '010-7766-3322',
    type: 'LESSEE',
    group: 'SEARCHING',
    memo: '뷰티샵/네일샵 확장이전 계획. 1층 또는 엘리베이터 있는 2층, 주차 편리한 곳.',
    createdAt: '2026-10-01T15:20:00Z',
    updatedAt: '2026-10-01T15:20:00Z',
    demands: [
      {
        id: 'dem-2',
        customerId: 'cust-5',
        targetPropertyType: 'STORE',
        targetTransactionType: '월세',
        targetRegion: '강남구 역삼/선릉 상권',
        minDeposit: 3000,
        maxDeposit: 5000,
        minMonthlyRent: 200,
        maxMonthlyRent: 350,
        preferredArea: 50,
        requirements: '권리금 3천만원 이하, 수도 배관 인입 필수',
        status: 'ACTIVE',
        createdAt: '2026-10-01T15:20:00Z',
        updatedAt: '2026-10-01T15:20:00Z',
      },
    ],
  },
];

export const INITIAL_PROPERTIES: PropertyItem[] = [
  {
    id: 'prop-1',
    propertyNumber: 'APT-2026-001',
    receiptDate: '2026-09-28',
    propertyType: 'APARTMENT',
    status: 'AVAILABLE',
    transactionType: '매매',
    address: '서울특별시 강남구 역삼로 310',
    detailAddress: '104동 1502호',
    direction: '남향',
    directionCriteria: '거실기준',
    availableDate: '2026-11-30',
    price: 185000,
    deposit: 0,
    monthlyRent: 0,
    consultationNotes: '로얄동 로얄층. 올확장 풀옵션 인테리어 2년 전 완료. 채광 최상.',
    landArea: 45.2,
    totalFloorArea: 114.5,
    approvalDate: '2019-06-15',
    buildingRegisterUse: '공동주택(아파트)',
    customerId: 'cust-1',
    customer: {
      id: 'cust-1',
      name: '김태호',
      phone: '010-8921-3450',
      carrier: 'SK',
      type: 'SELLER',
    },
    apartmentDetail: {
      complexName: '역삼 센트럴자이',
      buildingNo: '104동',
      unitNo: '1502호',
      supplyArea: 112.4,
      pyeongType: '34평형 A타입',
      exclusiveArea: 84.99,
      roomCount: 3,
      bathroomCount: 2,
      approvalDate: '2019-06-15',
      elevatorCount: 2,
      maintenanceFee: 25,
      heatingType: '도시가스(개별난방)',
      systemAircon: true,
      roomLivingOption: '방/거실 올확장형',
      heatExchanger: true,
      induction: true,
      otherOptions: '중문설치, 식기세척기 빌트인',
    },
    createdAt: '2026-09-28T09:30:00Z',
    updatedAt: '2026-09-28T09:30:00Z',
  },
  {
    id: 'prop-2',
    propertyNumber: 'STR-2026-012',
    receiptDate: '2026-09-29',
    propertyType: 'STORE',
    status: 'AVAILABLE',
    transactionType: '월세',
    address: '서울특별시 서초구 서초대로 350',
    detailAddress: '1층 102호',
    direction: '동향',
    directionCriteria: '주출입구기준',
    availableDate: '2026-11-01',
    deposit: 5000,
    monthlyRent: 350,
    consultationNotes: '유동인구 풍부한 먹자골목 코너자리. 기존 프랜차이즈 카페 성업중.',
    landArea: 120.0,
    totalFloorArea: 65.5,
    approvalDate: '2018-04-10',
    buildingRegisterUse: '제2종근린생활시설(일반음식점)',
    customerId: 'cust-2',
    customer: {
      id: 'cust-2',
      name: '박서연',
      phone: '010-3456-7890',
      carrier: 'KT',
      type: 'LESSOR',
    },
    storeDetail: {
      storeName: '달콤라떼 서초점',
      businessType: '휴게음식점(카페)',
      totalFloors: 5,
      currentFloor: '지상 1층',
      landArea: 120.0,
      buildingArea: 65.5,
      buildingUse: '제2종근린생활시설',
      actualArea: 62.0,
      roomCount: 0,
      bathroomCount: 1,
      approvalDate: '2018-04-10',
      parkingCount: 2,
      monthlyRentVat: true,
      premium: 4000,
      maintenanceFee: 30,
      maintenanceFeeVat: true,
      adminActionChecked: '행정처분 없음 (클린)',
      violationBuilding: '위반건축물 해당없음',
      operationPeriod: '3년 2개월 성업중',
      contractPeriod: '2년 보장 가능',
      parkingRequirement: '방문객 1시간 무료 주차 지원',
      businessRegistrationStatus: '본인 명의 정상 등록',
      rentIncreaseStatus: '직전 5% 인상 완료, 향후 법정 상한 준수',
      advertisementStatus: '온라인 및 오프라인 광고 동의',
      tableCountHall: 10,
      tableCountRoom: 0,
      employeeCount: 2,
      dailyRevenue: 95,
      equipmentStatus: '에스프레소 머신 및 제빙기 인수포함, 정수기 렌탈',
      liquorLoan: '해당없음',
      fireInspectionCert: '완비증명 보유 (다중이용업소)',
    },
    createdAt: '2026-09-29T14:15:00Z',
    updatedAt: '2026-09-29T14:15:00Z',
  },
  {
    id: 'prop-3',
    propertyNumber: 'OFF-2026-045',
    receiptDate: '2026-09-30',
    propertyType: 'OFFICE',
    status: 'AVAILABLE',
    transactionType: '월세',
    address: '서울특별시 강남구 테헤란로 142',
    detailAddress: '7층 전체',
    direction: '남동향',
    directionCriteria: '주출입구기준',
    availableDate: '2026-10-15',
    deposit: 8000,
    monthlyRent: 650,
    consultationNotes: '역삼역 도보 2분 초역세권 빌딩. 글래스 파티션 룸 3개, 탕비실, 대표실 완비.',
    landArea: 420.0,
    totalFloorArea: 210.0,
    approvalDate: '2020-09-15',
    buildingRegisterUse: '업무시설(사무소)',
    customerId: 'cust-3',
    customer: {
      id: 'cust-3',
      name: '이진우 대표',
      phone: '010-5678-1234',
      carrier: 'LG',
      type: 'LESSOR',
    },
    officeDetail: {
      officeName: '테크스페이스 빌딩 7F',
      totalFloors: 12,
      currentFloor: '지상 7층',
      landArea: 420.0,
      buildingArea: 210.0,
      buildingUse: '업무시설',
      actualArea: 185.0,
      roomCount: 4,
      bathroomCount: 2,
      approvalDate: '2020-09-15',
      parkingCount: 3,
      monthlyRentVat: true,
      maintenanceFee: 80,
      maintenanceFeeVat: true,
      violationBuilding: '위반사항 없음',
      parkingAndFee: '무료 2대 배정, 추가 1대당 월 15만원',
      rentIncreaseStatus: '2년 고정 계약 협의',
      advertisementStatus: '입간판 및 1층 로비 인포메이션 부착 가능',
      prosAndCons: '초역세권, 채광 우수하나 엘리베이터 점심시간 다소 혼잡',
      hvacSystem: '시스템 천장형 냉난방기 4대 개별제어',
      elevator: '승객용 2대, 비상용 1대',
      security: '지문인식 스피드게이트, 세콤 24시간',
      restorationScope: '원상복구 면제 협의(인테리어 승계 가능)',
      electricityExpansion: '현재 30kW 충분, 추가 10kW 증설 가능',
      specialTerms: '렌트프리 1개월 제공',
      totalOfficeCount: 15,
    },
    createdAt: '2026-09-30T11:00:00Z',
    updatedAt: '2026-09-30T11:00:00Z',
  },
];
